[build]
  command = "composer install --no-dev --prefer-dist --optimize-autoloader --ignore-platform-req=ext-pdo_mysql --no-scripts && npm ci && npm run build && php artisan filament:upgrade || true"
  publish = "public"

[build.environment]
  PHP_VERSION = "8.3"
  COMPOSER_ALLOW_SUPERUSER = "1"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200